--grants for tables
CREATE PROCEDURE GRANT_PRIV (
    USERNAME VARCHAR2, 
    GRANTEE VARCHAR2)
AS   
BEGIN
    FOR R IN (
        SELECT OWNER, TABLE_NAME 
        FROM ALL_TABLES 
        WHERE OWNER = USERNAME
    )
    LOOP
        EXECUTE IMMEDIATE 
            'GRANT SELECT, UPDATE, INSERT ON '||R.OWNER||'.'||R.TABLE_NAME||' to ' || GRANTEE;
    END LOOP;
END; 

--EXEC GRANT_PRIV_FOR_BL_DM('BL_3NF', 'BL_CL');


--grants for seuqences
CREATE OR REPLACE PROCEDURE GRANT_SEQ_USAGE(
    USERNAME VARCHAR2, 
    GRANTEE VARCHAR2)
AS   
BEGIN
    FOR R IN (
        SELECT SEQUENCE_OWNER, SEQUENCE_NAME 
        FROM ALL_SEQUENCES 
        WHERE SEQUENCE_OWNER = USERNAME
    )
    LOOP
        EXECUTE IMMEDIATE 
            'GRANT SELECT ON '||R.SEQUENCE_OWNER||'.'||R.SEQUENCE_NAME ||' TO ' || GRANTEE;
    END LOOP;
END; 

--EXEC GRANT_SEQ_USAGE_FOR_BL_DM('BL_3NF', 'BL_CL');


 