CREATE TABLE DIM_SALES_CHANNELS (
    SALES_CHANNEL_SURR_ID NUMBER (10) NOT NULL PRIMARY KEY,
    SALES_CHANNEL_ID      VARCHAR2(30) NOT NULL,
    SOURCE_SYSTEM         VARCHAR2(100) NOT NULL,
    SOURCE_TABLE          VARCHAR2(100) NOT NULL,
    SALES_CHANNEL_NAME    VARCHAR2(100) NOT NULL,
    INSERT_DT             DATE NOT NULL,
    UPDATE_DT             DATE NOT NULL 
);

CREATE TABLE DIM_PRODUCTS (
    PRODUCT_SURR_ID       NUMBER (10) NOT NULL PRIMARY KEY,
    PRODUCT_ID            VARCHAR2(30) NOT NULL,
    SOURCE_SYSTEM         VARCHAR2(100) NOT NULL,
    SOURCE_TABLE          VARCHAR2(100) NOT NULL,
    PRODUCT_NAME          VARCHAR2(100) NOT NULL,
    PRODUCT_CATEGORY_ID   NUMBER (10)   NOT NULL,
    PRODUCT_CATEGORY_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_PRICE         NUMBER (10) NOT NULL,
    INSERT_DT             DATE NOT NULL,
    UPDATE_DT             DATE NOT NULL 
);


CREATE TABLE DIM_STORES (
    STORE_SURR_ID      NUMBER (10) NOT NULL PRIMARY KEY,
    STORE_ID           VARCHAR2(30) NOT NULL,
    SOURCE_SYSTEM      VARCHAR2(100) NOT NULL,
    SOURCE_TABLE       VARCHAR2(100) NOT NULL,
    STORE_NAME         VARCHAR2(100) NOT NULL,
    CITY_ID            NUMBER (10)  NOT NULL,
    CITY_NAME          VARCHAR2(100) NOT NULL,
    CITY_DISTRICT_ID   NUMBER (10)  NOT NULL,
    CITY_DISTRICT_NAME VARCHAR2(100) NOT NULL,
    ADDRESS_LINE_DESC  VARCHAR2(100) NOT NULL,
    PHONE_NUMBER       VARCHAR2(100) NOT NULL,
    INSERT_DT          DATE NOT NULL,
    UPDATE_DT          DATE NOT NULL 
);


CREATE TABLE DIM_PAYMENT_TYPES (
    PAYMENT_TYPE_SURR_ID NUMBER (10) NOT NULL PRIMARY KEY,
    PAYMENT_TYPE_ID      VARCHAR2(30) NOT NULL,
    SOURCE_SYSTEM        VARCHAR2(100) NOT NULL,
    SOURCE_TABLE         VARCHAR2(100) NOT NULL,
    PAYMENT_TYPE_DESC    VARCHAR2(100) NOT NULL,
    INSERT_DT            DATE NOT NULL,
    UPDATE_DT            DATE NOT NULL 
);


CREATE TABLE DIM_DATE (
    DATE_ID                 NUMBER NOT NULL PRIMARY KEY,
    FULL_DATE               DATE,
    DAY_NUM                 VARCHAR2(2) NOT NULL,
    MONTH_NUM               VARCHAR2(2) NOT NULL,
    MONTH_NAME              VARCHAR2(36) NOT NULL,
    QUARTER                 VARCHAR2(7) NOT NULL,
    CALENDAR_YEAR           VARCHAR2(4) NOT NULL,
    INSERT_DT               DATE NOT NULL,
    UPDATE_DT               DATE NOT NULL 
);

CREATE TABLE DIM_EMPLOYEES_SCD (
    EMPLOYEE_SURR_ID NUMBER (10) NOT NULL,
    EMPLOYEE_ID      VARCHAR2(30) NOT NULL,
    SOURCE_SYSTEM    VARCHAR2(100) NOT NULL,
    SOURCE_TABLE     VARCHAR2(100) NOT NULL,
    FIRST_NAME       VARCHAR2(100) NOT NULL,
    LAST_NAME        VARCHAR2(100) NOT NULL,
    EMAIL            VARCHAR2(100) NOT NULL,
    PHONE_NUMBER     VARCHAR2(100) NOT NULL,
    JOB_TITLE_ID     NUMBER (10) NOT NULL,
    JOB_TITLE_DESC   VARCHAR2(100) NOT NULL,
    START_DT         DATE NOT NULL ,
    END_DT           DATE NOT NULL,
    IS_ACTIVE        VARCHAR2(50) NOT NULL,
    INSERT_DT        DATE NOT NULL,
    UPDATE_DT        DATE NOT NULL,
    CONSTRAINT primary_key  PRIMARY KEY (EMPLOYEE_SURR_ID, START_DT)
);


CREATE TABLE DIM_CUSTOMERS (
    CUSTOMER_SURR_ID    NUMBER (10) NOT NULL PRIMARY KEY,
    CUSTOMER_ID      	VARCHAR2(30)  NOT NULL,
    SOURCE_SYSTEM    	VARCHAR2(100) NOT NULL,
    SOURCE_TABLE     	VARCHAR2(100) NOT NULL,
    CUSTOMER_NAME    	VARCHAR2(100) NOT NULL,
    ADDRESS_LINE_DESC  	VARCHAR2(100) NOT NULL,
    CITY_DISTRICT_ID  	NUMBER (10) NOT NULL,
    CITY_DISTRICT_NAME  VARCHAR2(100) NOT NULL,
    CITY_ID            	NUMBER (10) NOT NULL,
    CITY_NAME           VARCHAR2(100) NOT NULL,
    EMAIL               VARCHAR2(100) NOT NULL,
    PHONE_NUMBER        VARCHAR2(100) NOT NULL,
    INSERT_DT           DATE NOT NULL,
    UPDATE_DT           DATE NOT NULL 
);

CREATE TABLE FCT_PAYMENTS (
    STORE_SURR_ID         NUMBER (10) NOT NULL,
    EMPLOYEE_SURR_ID      NUMBER (10) NOT NULL,
    CUSTOMER_SURR_ID      NUMBER (10) NOT NULL,
    PRODUCT_SURR_ID       NUMBER (10) NOT NULL,
    SALES_CHANNEL_SURR_ID NUMBER (10) NOT NULL,
    PAYMENT_TYPE_SURR_ID  NUMBER (10) NOT NULL,
    DATE_ID               NUMBER (10) NOT NULL,
    AMOUNT_PAID           NUMBER(10, 2) NOT NULL,
    PRODUCT_QTY           NUMBER (10) NOT NULL,
    ORDER_NO              VARCHAR2(100) NOT NULL,
    INSERT_DT             DATE NOT NULL,
    UPDATE_DT             DATE NOT NULL
);

