CREATE PROCEDURE GRANT_SELECT (
    USERNAME VARCHAR2, 
    GRANTEE VARCHAR2)
AS   
BEGIN
    FOR R IN (
        SELECT OWNER, TABLE_NAME 
        FROM ALL_TABLES 
        WHERE OWNER = USERNAME
    )
    LOOP
        EXECUTE IMMEDIATE 
            'GRANT SELECT ON '||R.OWNER||'.'||R.TABLE_NAME||' to ' || GRANTEE;
    END LOOP;
END; 

--EXEC GRANT_SELECT ('SA_SOURCE', 'BL_CL');

CREATE PROCEDURE GRANT_PRIV_FOR_BL_DM (
    USERNAME VARCHAR2, 
    GRANTEE VARCHAR2)
AS   
BEGIN
    FOR R IN (
        SELECT OWNER, TABLE_NAME 
        FROM ALL_TABLES 
        WHERE OWNER = USERNAME
    )
    LOOP
        EXECUTE IMMEDIATE 
            'GRANT SELECT, UPDATE, INSERT ON '||R.OWNER||'.'||R.TABLE_NAME||' to ' || GRANTEE;
    END LOOP;
END; 

--EXEC GRANT_PRIV_FOR_BL_DM('SA_SOURCE', 'BL_CL');

   
--works
GRANT SELECT ON BL_3NF.JOBS_SEQ TO BL_CL;    

GRANT SELECT ON BL_3NF.PRODUCT_SEQ TO BL_CL;    



--for seuqence grants 
CREATE OR REPLACE PROCEDURE GRANT_SEQ_USAGE_FOR_BL_DM (
    USERNAME VARCHAR2, 
    GRANTEE VARCHAR2)
AS   
BEGIN
    FOR R IN (
        SELECT SEQUENCE_OWNER, SEQUENCE_NAME 
        FROM ALL_SEQUENCES 
        WHERE SEQUENCE_OWNER = USERNAME
    )
    LOOP
        EXECUTE IMMEDIATE 
            'GRANT SELECT ON '||R.SEQUENCE_OWNER||'.'||R.SEQUENCE_NAME ||' TO ' || GRANTEE;
    END LOOP;
END; 

--EXEC GRANT_SEQ_USAGE_FOR_BL_DM('BL_DM', 'BL_CL');




--for seuqence grants (not flexible)
CREATE OR REPLACE PROCEDURE GRANT_SEQ_USAGE (
    USERNAME VARCHAR2, 
    GRANTEE VARCHAR2)
AS   
BEGIN
    FOR R IN (
        SELECT SEQUENCE_NAME 
        FROM USER_SEQUENCES 
        WHERE SEQUENCE_NAME like 'DIM%'
    )
    LOOP
        EXECUTE IMMEDIATE 
            'GRANT SELECT ON '||USERNAME||'.'||R.SEQUENCE_NAME ||' to ' || GRANTEE;
    END LOOP;
END; 





select * from all_sequences;

SELECT SEQUENCE_NAME, LAST_NUMBER, MAX_VALUE, INCREMENT_BY FROM USER_SEQUENCES; 
 
GRANT SELECT ON SCHEMA_NAME.SEQUENCE_NAME TO USER_OR_ROLE_NAME;
 
SELECT * FROM ALL_TAB_PRIVS WHERE TABLE_NAME = 'sequence_name';
 
 
 