CREATE OR REPLACE PACKAGE BODY PKG_LOAD_DIM_SALES_CHANNELS AS

PROCEDURE PROC_LOAD_DIM_SALES_CHANNELS IS

    L_PROCEDURE_NAME    VARCHAR2(2000) := 'PROC_LOAD_DIM_SALES_CHANNELS';
    L_TABLE_NAME        VARCHAR2(2000) := 'DIM_SALES_CHANNELS';
    L_ROWS_PROCESSED    NUMBER;
    L_CONTEXT           VARCHAR2(2000) := 'LOADING DIM_SALES_CHANNELS STARTS';
    TYPE t_ref_c IS REF CURSOR;
    ref_cur    t_ref_c;     
    
BEGIN

OPEN ref_cur FOR 'SELECT COUNT(*)FROM DL_DM.DIM_SALES_CHANNELS';

FETCH ref_cur INTO L_ROW_COUNT_BEFORE;
CLOSE ref_cur;

PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE STARTS', L_ROW_COUNT_BEFORE, SYSDATE);

MERGE INTO BL_DM.DIM_SALES_CHANNELS TARG
USING 
       (SELECT 
            TO_CHAR(SALES_CHANNEL_ID) AS SALES_CHANNEL_ID,
            SOURCE_SYSTEM,
            SOURCE_TABLE,
            SALES_CHANNEL_NAME,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
            BL_3NF.CE_SALES_CHANNELS) SRC
ON  (TARG.SALES_CHANNEL_ID = SRC.SALES_CHANNEL_ID
AND TARG.SOURCE_SYSTEM = SRC.SOURCE_SYSTEM
AND TARG.SOURCE_TABLE = SRC.SOURCE_TABLE)
WHEN MATCHED THEN UPDATE SET 
    TARG.SALES_CHANNEL_NAME = SRC.SALES_CHANNEL_NAME,
    TARG.UPDATE_DT = SYSDATE
WHERE TARG.SALES_CHANNEL_NAME <> SRC.SALES_CHANNEL_NAME
WHEN NOT MATCHED THEN INSERT 
    (SALES_CHANNEL_SURR_ID, 
    SALES_CHANNEL_ID, 
    SOURCE_SYSTEM, 
    SOURCE_TABLE, 
    SALES_CHANNEL_NAME,
    INSERT_DT, 
    UPDATE_DT)
VALUES (BL_DM.dim_sales_ch_seq.NEXTVAL, 
    NVL(SRC.SALES_CHANNEL_ID, 'n/a'), 
    SRC.SOURCE_SYSTEM, 
    SRC.SOURCE_TABLE,
    NVL(SRC.SALES_CHANNEL_NAME, 'n/a'), 
    SYSDATE, 
    SYSDATE);

L_ROWS_PROCESSED := SQL%ROWCOUNT;
L_CONTEXT := 'LOADING DIM_SALES_CHANNELS FINISHED';
PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE END', L_ROWS_PROCESSED, SYSDATE);

COMMIT;

EXCEPTION 
    WHEN OTHERS THEN 
        L_CONTEXT := 'ERROR LOADING DIM_SALES_CHANNELS';
        PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'ERROR', NULL, SYSDATE);
        ROLLBACK;
        RAISE;
    
END PROC_LOAD_DIM_SALES_CHANNELS;
          
BEGIN
PROC_LOAD_DIM_SALES_CHANNELS;
END;

