CREATE OR REPLACE PACKAGE BODY PKG_LOAD_DIM_PAYMENT_TYPES AS

PROCEDURE PROC_LOAD_DIM_PAYMENT_TYPES IS

    L_PROCEDURE_NAME    VARCHAR2(2000) := 'PROC_LOAD_DIM_PAYMENT_TYPES';
    L_TABLE_NAME        VARCHAR2(2000) := 'DIM_PAYMENT_TYPES';
    L_ROWS_PROCESSED    NUMBER;
    L_CONTEXT           VARCHAR2(2000) := 'LOADING DIM_PAYMENT_TYPES STARTS';
    TYPE t_ref_c IS REF CURSOR;
    ref_cur    t_ref_c;     
    
BEGIN

OPEN ref_cur FOR 'SELECT COUNT(*)FROM DL_DM.DIM_PAYMENT_TYPES';

FETCH ref_cur INTO L_ROW_COUNT_BEFORE;
CLOSE ref_cur;

PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE STARTS', L_ROW_COUNT_BEFORE, SYSDATE);

MERGE INTO BL_DM.DIM_PAYMENT_TYPES TARG
USING 
       (SELECT 
            TO_CHAR(PAYMENT_TYPE_ID) AS PAYMENT_TYPE_ID,
            SOURCE_SYSTEM,
            SOURCE_TABLE,
            PAYMENT_TYPE_DESC,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
            BL_3NF.CE_PAYMENT_TYPES) SRC
ON  (TARG.PAYMENT_TYPE_ID = SRC.PAYMENT_TYPE_ID
AND TARG.SOURCE_SYSTEM = SRC.SOURCE_SYSTEM
AND TARG.SOURCE_TABLE = SRC.SOURCE_TABLE)
WHEN MATCHED THEN UPDATE SET 
    TARG.PAYMENT_TYPE_DESC = SRC.PAYMENT_TYPE_DESC,
    TARG.UPDATE_DT = SYSDATE
WHERE TARG.PAYMENT_TYPE_DESC <> SRC.PAYMENT_TYPE_DESC
WHEN NOT MATCHED THEN INSERT 
    (PAYMENT_TYPE_SURR_ID, 
    PAYMENT_TYPE_ID, 
    SOURCE_SYSTEM, 
    SOURCE_TABLE, 
    PAYMENT_TYPE_DESC,
    INSERT_DT, 
    UPDATE_DT)
VALUES (BL_DM.DIM_PAY_TYPE_SEQ.NEXTVAL, 
    NVL(SRC.PAYMENT_TYPE_ID, 'n/a'), 
    SRC.SOURCE_SYSTEM, 
    SRC.SOURCE_TABLE,
    NVL(SRC.PAYMENT_TYPE_DESC, 'n/a'), 
    SYSDATE, 
    SYSDATE);

L_ROWS_PROCESSED := SQL%ROWCOUNT;
L_CONTEXT := 'LOADING DIM_PAYMENT_TYPES FINISHED';
PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE END', L_ROWS_PROCESSED, SYSDATE);

COMMIT;

EXCEPTION 
    WHEN OTHERS THEN 
        L_CONTEXT := 'ERROR LOADING DIM_PAYMENT_TYPES';
        PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'ERROR', NULL, SYSDATE);
        ROLLBACK;
        RAISE;
    
END PROC_LOAD_DIM_PAYMENT_TYPES;
          
BEGIN
PROC_LOAD_DIM_PAYMENT_TYPES;
END;
