CREATE OR REPLACE PACKAGE BODY PKG_LOAD_DIM_PRODUCTS AS

PROCEDURE PROC_LOAD_DIM_PRODUCTS IS

    L_PROCEDURE_NAME    VARCHAR2(2000) := 'PROC_LOAD_DIM_PRODUCTS';
    L_TABLE_NAME        VARCHAR2(2000) := 'DIM_PRODUCTS';
    L_ROWS_PROCESSED    NUMBER;
    L_CONTEXT           VARCHAR2(2000) := 'LOADING DIM_PRODUCTS STARTS';
    TYPE t_ref_c IS REF CURSOR;
    ref_cur    t_ref_c;     
    
BEGIN

OPEN ref_cur FOR 'SELECT COUNT(*)FROM DL_DM.DIM_PRODUCTS';

FETCH ref_cur INTO L_ROW_COUNT_BEFORE;
CLOSE ref_cur;

PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE STARTS', L_ROW_COUNT_BEFORE, SYSDATE);

MERGE INTO BL_DM.DIM_PRODUCTS TARG
USING 
       (SELECT 
            TO_CHAR(PRODUCT_ID) AS PRODUCT_ID,
            P.SOURCE_SYSTEM,
            P.SOURCE_TABLE,
            P.PRODUCT_NAME,
            P.PRODUCT_PRICE,
            TO_CHAR(P.PRODUCT_CATEGORY_ID) AS PRODUCT_CATEGORY_ID, 
            PT.PRODUCT_CATEGORY_NAME
        FROM
             BL_3NF.CE_PRODUCTS P 
             JOIN BL_3NF.CE_PRODUCT_CATEGORIES PT ON PT.PRODUCT_CATEGORY_ID = P.PRODUCT_CATEGORY_ID
             WHERE P.SOURCE_SYSTEM = PT.SOURCE_SYSTEM
             AND P.SOURCE_TABLE = PT.SOURCE_TABLE) SRC
ON  (TARG.PRODUCT_ID = SRC.PRODUCT_ID
AND TARG.SOURCE_SYSTEM = SRC.SOURCE_SYSTEM
AND TARG.SOURCE_TABLE = SRC.SOURCE_TABLE)
WHEN MATCHED THEN UPDATE SET 
    TARG.PRODUCT_NAME = SRC.PRODUCT_NAME,
    TARG.PRODUCT_PRICE = SRC.PRODUCT_PRICE,
    TARG.PRODUCT_CATEGORY_ID = SRC.PRODUCT_CATEGORY_ID,
    TARG.PRODUCT_CATEGORY_NAME = SRC.PRODUCT_CATEGORY_NAME,
    TARG.UPDATE_DT = SYSDATE
WHERE    TARG.PRODUCT_NAME <> SRC.PRODUCT_NAME 
    OR TARG.PRODUCT_PRICE <> SRC.PRODUCT_PRICE
    OR TARG.PRODUCT_CATEGORY_ID <> SRC.PRODUCT_CATEGORY_ID
    OR TARG.PRODUCT_CATEGORY_NAME <> SRC.PRODUCT_CATEGORY_NAME
WHEN NOT MATCHED THEN INSERT 
    (PRODUCT_SURR_ID, 
    PRODUCT_ID, 
    SOURCE_SYSTEM, 
    SOURCE_TABLE, 
    PRODUCT_NAME,
    PRODUCT_CATEGORY_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_PRICE,
    INSERT_DT, 
    UPDATE_DT)
VALUES (BL_DM.DIM_PROD_SEQ.NEXTVAL, 
    NVL(SRC.PRODUCT_ID, 'n/a'), 
    SRC.SOURCE_SYSTEM, 
    SRC.SOURCE_TABLE,
    NVL(SRC.PRODUCT_NAME, 'n/a'), 
    SRC.PRODUCT_CATEGORY_ID,
    SRC.PRODUCT_CATEGORY_NAME,
    SRC.PRODUCT_PRICE,
    SYSDATE, 
    SYSDATE);

L_ROWS_PROCESSED := SQL%ROWCOUNT;
L_CONTEXT := 'LOADING DIM_PRODUCTS FINISHED';
PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE END', L_ROWS_PROCESSED, SYSDATE);

COMMIT;

EXCEPTION 
    WHEN OTHERS THEN 
        L_CONTEXT := 'ERROR LOADING DIM_PRODUCTS';
        PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'ERROR', NULL, SYSDATE);
        ROLLBACK;
        RAISE;
    
END PROC_LOAD_DIM_PRODUCTS;
          
BEGIN
PROC_LOAD_DIM_PRODUCTS;
END;

