-------------------------------
CREATE OR REPLACE PACKAGE BODY PKG_LOAD_3NF_CE_JOB_TITLES AS

PROCEDURE PROC_LOAD_CE_JOB_TITLES IS
    L_PROCEDURE_NAME    VARCHAR2(2000) := 'PROC_LOAD_CE_JOB_TITLES';
    L_TABLE_NAME        VARCHAR2(2000) := 'CE_JOB_TITLES';
    L_ROWS_PROCESSED    NUMBER;
    L_CONTEXT           VARCHAR2(2000) := 'LOADING CE_JOB_TITLES';
    L_ROW_COUNT_BEFORE  NUMBER;
    L_ROW_COUNT_AFTER   NUMBER;
    TYPE t_ref_c IS REF CURSOR;
    ref_cur    t_ref_c;      
    
BEGIN

OPEN ref_cur FOR 'SELECT COUNT(*)FROM BL_3NF.CE_JOB_TITLES';

FETCH ref_cur INTO L_ROW_COUNT_BEFORE;
CLOSE ref_cur;

PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE STARTS', L_ROW_COUNT_BEFORE, SYSDATE);

MERGE INTO BL_3NF.CE_JOB_TITLES  TARG
USING 
       (SELECT DISTINCT
            TRIM(JOB_TITLE) AS JOB_TITLE_SRCID, 
            TRIM(JOB_TITLE) AS JOB_TITLE_DESC,
            'business_entities' AS  SOURCE_SYSTEM,
            'src_business_entities' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
            SRC_BUSINESS_ENTITIES
        UNION ALL
        SELECT DISTINCT
            TRIM(JOB_TITLE) AS JOB_TITLE_SRCID, 
            TRIM(JOB_TITLE) AS JOB_TITLE_DESC,
            'individual_customers' AS  SOURCE_SYSTEM,
            'src_individual_customers' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
             SRC_INDIVIDUAL_CUSTOMERS) SRC
ON  (TARG.JOB_TITLE_SRCID = SRC.JOB_TITLE_SRCID
    AND TARG.SOURCE_SYSTEM = SRC.SOURCE_SYSTEM
    AND TARG.SOURCE_TABLE = SRC.SOURCE_TABLE)
WHEN MATCHED THEN UPDATE SET 
    TARG.JOB_TITLE_DESC = SRC.JOB_TITLE_DESC,
    TARG.UPDATE_DT = SYSDATE
    WHERE TARG.JOB_TITLE_DESC <> SRC.JOB_TITLE_DESC
WHEN NOT MATCHED THEN INSERT 
    (JOB_TITLE_ID, 
    JOB_TITLE_SRCID, 
    JOB_TITLE_DESC, 
    SOURCE_SYSTEM, 
    SOURCE_TABLE, 
    INSERT_DT, 
    UPDATE_DT)
VALUES (BL_3NF.JOBS_SEQ.NEXTVAL, 
    NVL(SRC.JOB_TITLE_SRCID, 'n/a'), 
    NVL(SRC.JOB_TITLE_DESC, 'n/a'), 
    SRC.SOURCE_SYSTEM, 
    SRC.SOURCE_TABLE,
    SYSDATE, 
    SYSDATE);
    
L_ROWS_PROCESSED := SQL%ROWCOUNT;
L_CONTEXT := 'LOADING CE_JOB_TITLES FINISHED';
PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE END', L_ROWS_PROCESSED, SYSDATE);

COMMIT;

EXCEPTION 
    WHEN OTHERS THEN 
        L_CONTEXT := 'ERROR LOADING CE_JOB_TITLES';
        PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'ERROR', NULL, SYSDATE);
        ROLLBACK;
        RAISE;

END PROC_LOAD_CE_JOB_TITLES;

END PKG_LOAD_3NF_CE_JOB_TITLES;         
/
