-------------------------------
CREATE OR REPLACE PACKAGE BODY PKG_LOAD_3NF_CE_PRODUCT_CATEGORIES AS

PROCEDURE PROC_LOAD_CE_PRODUCT_CATEGORIES IS
    L_PROCEDURE_NAME    VARCHAR2(2000) := 'PROC_LOAD_CE_PRODUCT_CATEGORIES';
    L_TABLE_NAME        VARCHAR2(2000) := 'CE_PRODUCT_CATEGORIES';
    L_ROWS_PROCESSED    NUMBER;
    L_CONTEXT           VARCHAR2(2000) := 'LOADING CE_PRODUCT_CATEGORIES';
    L_ROW_COUNT_BEFORE  NUMBER;
    L_ROW_COUNT_AFTER   NUMBER;
    TYPE t_ref_c IS REF CURSOR;
    ref_cur    t_ref_c;     
    
BEGIN

OPEN ref_cur FOR 'SELECT COUNT(*)FROM BL_3NF.CE_PRODUCT_CATEGORIES';

FETCH ref_cur INTO L_ROW_COUNT_BEFORE;
CLOSE ref_cur;

PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE STARTS', L_ROW_COUNT_BEFORE, SYSDATE);

MERGE INTO BL_3NF.CE_PRODUCT_CATEGORIES TARG
USING 
       (SELECT DISTINCT
            TRIM(PROCUCT_CATEGORY) AS PRODUCT_CATEGORY_SRCID, 
            TRIM(PROCUCT_CATEGORY) AS PRODUCT_CATEGORY_NAME,
            'business_entities' AS  SOURCE_SYSTEM,
            'src_business_entities' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
            SRC_BUSINESS_ENTITIES
       UNION ALL
        SELECT DISTINCT
            TRIM(PROCUCT_CATEGORY) AS PRODUCT_CATEGORY_SRCID, 
            TRIM(PROCUCT_CATEGORY) AS PRODUCT_CATEGORY_NAME,
            'individual_customers' AS  SOURCE_SYSTEM,
            'src_individual_customers' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
             SRC_INDIVIDUAL_CUSTOMERS) SRC
ON  (TARG.PRODUCT_CATEGORY_SRCID = SRC.PRODUCT_CATEGORY_SRCID
AND TARG.SOURCE_SYSTEM = SRC.SOURCE_SYSTEM
AND TARG.SOURCE_TABLE = SRC.SOURCE_TABLE)
WHEN MATCHED THEN UPDATE SET 
    TARG.PRODUCT_CATEGORY_NAME = SRC.PRODUCT_CATEGORY_NAME,
    TARG.UPDATE_DT = SYSDATE
    WHERE TARG.PRODUCT_CATEGORY_NAME <> SRC.PRODUCT_CATEGORY_NAME
WHEN NOT MATCHED THEN INSERT 
    (PRODUCT_CATEGORY_ID, 
    PRODUCT_CATEGORY_SRCID, 
    PRODUCT_CATEGORY_NAME, 
    SOURCE_SYSTEM, 
    SOURCE_TABLE, 
    INSERT_DT, 
    UPDATE_DT)
VALUES (BL_3NF.PRODUCT_SEQ.NEXTVAL, 
    NVL(SRC.PRODUCT_CATEGORY_SRCID, 'n/a'), 
    NVL(SRC.PRODUCT_CATEGORY_NAME, 'n/a'),
    SRC.SOURCE_SYSTEM, 
    SRC.SOURCE_TABLE,
    SYSDATE, 
    SYSDATE);
    
L_ROWS_PROCESSED := SQL%ROWCOUNT;
L_CONTEXT := 'LOADING CE_PRODUCT_CATEGORIES FINISHED';
PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE END', L_ROWS_PROCESSED, SYSDATE);

COMMIT;

EXCEPTION 
    WHEN OTHERS THEN 
        L_CONTEXT := 'ERROR LOADING CE_PRODUCT_CATEGORIES';
        PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'ERROR', NULL, SYSDATE);
        ROLLBACK;
        RAISE;

END PROC_LOAD_CE_PRODUCT_CATEGORIES;

END PKG_LOAD_3NF_CE_PRODUCT_CATEGORIES;           
/
