-------------------------------
CREATE OR REPLACE PACKAGE BODY PKG_LOAD_3NF_CE_SALES_CHANNELS AS

PROCEDURE PROC_LOAD_CE_SALES_CHANNELS IS
    L_PROCEDURE_NAME    VARCHAR2(2000) := 'PROC_LOAD_CE_SALES_CHANNELS';
    L_TABLE_NAME        VARCHAR2(2000) := 'CE_SALES_CHANNELS';
    L_ROWS_PROCESSED    NUMBER;
    L_CONTEXT           VARCHAR2(2000) := 'LOADING CE_SALES_CHANNELS';
    L_ROW_COUNT_BEFORE  NUMBER;
    L_ROW_COUNT_AFTER   NUMBER;
    TYPE t_ref_c IS REF CURSOR;
    ref_cur    t_ref_c;     
    
BEGIN

OPEN ref_cur FOR 'SELECT COUNT(*)FROM BL_3NF.CE_SALES_CHANNELS';

FETCH ref_cur INTO L_ROW_COUNT_BEFORE;
CLOSE ref_cur;

PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE STARTS', L_ROW_COUNT_BEFORE, SYSDATE);    

MERGE INTO BL_3NF.CE_SALES_CHANNELS TARG
USING 
       (SELECT DISTINCT
            TRIM(SALES_CHANNEL) AS SALES_CHANNEL_NAME, 
            TRIM(SALES_CHANNEL_ID) AS SALES_CHANNEL_SRCID,
            'business_entities' AS  SOURCE_SYSTEM,
            'src_business_entities' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
            SRC_BUSINESS_ENTITIES
        UNION ALL
        SELECT DISTINCT
             TRIM(SALES_CHANNEL) AS SALES_CHANNEL_NAME, 
             TRIM(SALES_CHANNEL_ID) AS SALES_CHANNEL_SRCID,
            'individual_customers' AS SOURCE_SYSTEM,
            'src_individual_customers' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
             SRC_INDIVIDUAL_CUSTOMERS) SRC
ON  (TARG.SALES_CHANNEL_SRCID = SRC.SALES_CHANNEL_SRCID
    AND TARG.SOURCE_SYSTEM = SRC.SOURCE_SYSTEM
    AND TARG.SOURCE_TABLE = SRC.SOURCE_TABLE)
WHEN MATCHED THEN UPDATE SET 
    TARG.SALES_CHANNEL_NAME = SRC.SALES_CHANNEL_NAME,
    TARG.UPDATE_DT = SYSDATE
    WHERE TARG.SALES_CHANNEL_NAME <> SRC.SALES_CHANNEL_NAME
WHEN NOT MATCHED THEN INSERT 
    (SALES_CHANNEL_ID, 
    SALES_CHANNEL_NAME, 
    SALES_CHANNEL_SRCID, 
    SOURCE_SYSTEM, 
    SOURCE_TABLE, 
    INSERT_DT, 
    UPDATE_DT)
VALUES (BL_3NF.CHANNEL_SEQ.NEXTVAL,
    NVL(SRC.SALES_CHANNEL_NAME, 'n/a'), 
    NVL(SRC.SALES_CHANNEL_SRCID, 'n/a'), 
    SRC.SOURCE_SYSTEM, 
    SRC.SOURCE_TABLE,
    SYSDATE, 
    SYSDATE);
    
L_ROWS_PROCESSED := SQL%ROWCOUNT;
L_CONTEXT := 'LOADING CE_SALES_CHANNELS FINISHED';
PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE END', L_ROWS_PROCESSED, SYSDATE);

COMMIT;

EXCEPTION 
    WHEN OTHERS THEN 
        L_CONTEXT := 'ERROR LOADING CE_SALES_CHANNELS';
        PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'ERROR', NULL, SYSDATE);
        ROLLBACK;
        RAISE;

END PROC_LOAD_CE_SALES_CHANNELS;

END PKG_LOAD_3NF_CE_SALES_CHANNELS;           
/
