-------------------------------
CREATE OR REPLACE PACKAGE BODY PKG_LOAD_3NF_CE_PAYMENT_TYPES AS

PROCEDURE PROC_LOAD_CE_PAYMENT_TYPES IS
    L_PROCEDURE_NAME    VARCHAR2(2000) := 'PROC_LOAD_CE_PAYMENT_TYPES ';
    L_TABLE_NAME        VARCHAR2(2000) := 'CE_PAYMENT_TYPES ';
    L_ROWS_PROCESSED    NUMBER;
    L_CONTEXT           VARCHAR2(2000) := 'LOADING CE_PAYMENT_TYPES STARTS';
    L_ROW_COUNT_BEFORE  NUMBER;
    L_ROW_COUNT_AFTER   NUMBER;
    TYPE t_ref_c IS REF CURSOR;
    ref_cur    t_ref_c;     
      
BEGIN

OPEN ref_cur FOR 'SELECT COUNT(*)FROM BL_3NF.CE_PAYMENT_TYPES';

FETCH ref_cur INTO L_ROW_COUNT_BEFORE;
CLOSE ref_cur;

PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE STARTS', L_ROW_COUNT_BEFORE, SYSDATE);        

MERGE INTO BL_3NF.CE_PAYMENT_TYPES TARG
USING 
       (SELECT DISTINCT
             TRIM(PAYMENT_TYPE) AS PAYMENT_TYPE_SRCID, 
             TRIM(PAYMENT_TYPE) AS PAYMENT_TYPE_DESC,
            'business_entities' AS  SOURCE_SYSTEM,
            'scr_business_entities' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
            SRC_BUSINESS_ENTITIES
        UNION ALL
        SELECT DISTINCT
             TRIM(PAYMENT_TYPE) AS PAYMENT_TYPE_SRCID, 
             TRIM(PAYMENT_TYPE) AS PAYMENT_TYPE_DESC,
            'individual_customers' AS  SOURCE_SYSTEM,
            'scr_individual_customers' AS SOURCE_TABLE,
            SYSDATE AS INSERT_DT,
            SYSDATE AS UPDATE_DT
        FROM
             SRC_INDIVIDUAL_CUSTOMERS) SRC
ON  (TARG.PAYMENT_TYPE_SRCID = SRC.PAYMENT_TYPE_DESC
    AND TARG.SOURCE_SYSTEM = SRC.SOURCE_SYSTEM
    AND TARG.SOURCE_TABLE = SRC.SOURCE_TABLE)
WHEN MATCHED THEN UPDATE SET 
    TARG.PAYMENT_TYPE_DESC = SRC.PAYMENT_TYPE_DESC,
    TARG.UPDATE_DT = SYSDATE
    WHERE TARG.PAYMENT_TYPE_DESC <> SRC.PAYMENT_TYPE_DESC
WHEN NOT MATCHED THEN INSERT 
    (PAYMENT_TYPE_ID, 
    PAYMENT_TYPE_SRCID, 
    PAYMENT_TYPE_DESC,
    SOURCE_SYSTEM, 
    SOURCE_TABLE, 
    INSERT_DT, 
    UPDATE_DT)
VALUES (BL_3NF.PAYMENT_SEQ.NEXTVAL, 
    NVL(SRC.PAYMENT_TYPE_SRCID, 'n/a'), 
    NVL(SRC.PAYMENT_TYPE_DESC, 'n/a'), 
    SRC.SOURCE_SYSTEM, 
    SRC.SOURCE_TABLE,
    SYSDATE, 
    SYSDATE);

L_ROWS_PROCESSED := SQL%ROWCOUNT;
L_CONTEXT := 'LOADING CE_PAYMENT_TYPES FINISHED';
PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'PROCEDURE END', L_ROWS_PROCESSED, SYSDATE);

COMMIT;

EXCEPTION 
    WHEN OTHERS THEN 
        L_CONTEXT := 'ERROR LOADING CE_PAYMENT_TYPES';
        PROC_LOG(L_PACKAGE_NAME, L_PROCEDURE_NAME, L_TABLE_NAME, L_CONTEXT, 'ERROR', NULL, SYSDATE);
        ROLLBACK;
        RAISE;

END PROC_LOAD_CE_PAYMENT_TYPES;  

END PKG_LOAD_3NF_CE_PAYMENT_TYPES;           
/
